#! /bin/sh

# Author: Thomas Debesse
# License: CC0 1.0
# https://creativecommons.org/publicdomain/zero/1.0/

if [ -z "${1}" ]
then
	printf 'ERROR: missing seed\n' >&2
	exit 1
fi

seed="${1}"
map_name="tremgen-${seed}"

source_dpkdir="src/map-${map_name}_src.dpkdir"
resource_dpkdir='src/res-tremgen_src.dpkdir'

cd set

if [ ! -d "${source_dpkdir}" ]
then
	printf 'ERROR: not a directory: %s\n' "${source_dpkdir}" >&2
	exit 1
fi

urcheon build -cm "${resource_dpkdir}" "${source_dpkdir}"

#EOF
