#! /bin/sh

# Author: Thomas Debesse
# License: CC0 1.0
# https://creativecommons.org/publicdomain/zero/1.0/

writeArenaFile () {
	sed -e 's/\\t/\t/g' > "${3}" <<-EOF
	{
	\tmap "${2}"
	\tlongname "TremGen#${1}"
	\ttype "tremulous"
	}
	EOF
}

writeGameFile () {
	cat > "${1}" <<-EOF
	unvanquished
	EOF
}

writeDepsFile () {
	cat > "${1}" <<-EOF
	res-tremgen
	EOF
}

if [ -z "${1}" ]
then
	seed="$(date +%N)"
else
	seed="${1}"
fi

map_name="tremgen-${seed}"

source_dpkdir="set/src/map-${map_name}_src.dpkdir"
deps_file="${source_dpkdir}/DEPS"

maps_dir="${source_dpkdir}/maps"
map_file="${maps_dir}/${map_name}.map"

meta_dir="${source_dpkdir}/meta/${map_name}"
levelshot_file="${meta_dir}/${map_name}.tga"
arena_file="${meta_dir}/${map_name}.arena"

urcheon_dir="${source_dpkdir}/.urcheon"
game_file="${urcheon_dir}/game.txt"

mkdir -p "${maps_dir}"
./tremgen "${seed}" "${map_file}"
writeDepsFile "${deps_file}"

mkdir -p "${meta_dir}"
./minimap "${map_name}" "${levelshot_file}"
writeArenaFile "${seed}" "${map_name}" "${arena_file}"

mkdir -p "${urcheon_dir}"
writeGameFile "${game_file}"

#EOF
