///definition des constantes des texutres


#define TEXTURE_SKYBOX (-10)
#define TEXTURE_ALPHA_100 (-12)
#define TEXTURE_ALPHA_50 (-11)
#define TEXTURE_WATER_CAULK (-3)
#define TEXTURE_SKIP (-2)
#define TEXTURE_CAULK (-1)
#define TEXTURE_HINT 81

#define TEXTURE_TER1 1
#define TEXTURE_TER2 2
#define TEXTURE_TER3 4
#define TEXTURE_TER4 8
#define TEXTURE_TER5 16


#define TEXTURE_TER1_2 TEXTURE_TER1+TEXTURE_TER2
#define TEXTURE_TER1_3 TEXTURE_TER1+TEXTURE_TER3
#define TEXTURE_TER1_4 TEXTURE_TER1+TEXTURE_TER4
#define TEXTURE_TER1_5 TEXTURE_TER1+TEXTURE_TER5


#define TEXTURE_TER2_3 TEXTURE_TER2+TEXTURE_TER3
#define TEXTURE_TER2_4 TEXTURE_TER2+TEXTURE_TER4
#define TEXTURE_TER2_5 TEXTURE_TER2+TEXTURE_TER5


#define TEXTURE_TER3_4 TEXTURE_TER3+TEXTURE_TER4
#define TEXTURE_TER3_5 TEXTURE_TER3+TEXTURE_TER5

#define TEXTURE_TER4_5 TEXTURE_TER4+TEXTURE_TER5

//majore par TEXTURE_TER4_5 la 24

#define TEXTURE_WATER 80 

